### ISSUE TITLE
Welcome!

### ISSUE THREAD

**Issue by darquezt** [Gamote/lottie-react#1]
Hi! First of all, thanks a lot for making this library! I was about to do the same when I found this repo. I have been using Lottie a lot in my react native project and I wanted to use it also in my react projects.

I have a few questions though. Is there any particular reason of why naming the component Animator? I mean, I'd prefer the API to feel the same as when using lottie-react-native (where the component is exported default so you can name it whatever you want, although is usually named LottieView). Why not going with just Lottie?

Also, I could not think of a use case for the useAnimator hook, would you give an example of why it is needed or useful?

Lastly, I really look forward for this to be a commonly used library so I would like to offer you my help in getting it there. Let me know if I can help ;)

**Comment by Gamote** [comment]
Hi @darquezt,

I am glad that you find this library useful and thank you for your offer to help, feel free to send us more suggestions or MRs.

Also you've raised some good questions:
- we are already working on a new version which will export the Lottie view component as default
- the `useAnimator` hook will be the core of this library and it will be used mainly by the lottie component. Also the hook will come in handy when the developers don't want to use `ref` objects in order to have access to the interaction methods.

**Comment by Gamote** [comment]
v1.1.0

**Comment by darquezt** [comment]
Hello again! thanks for the quick reply. I see know why the hook will be useful. However, I think the version you just released is not exporting `useLottie` 😱 

I haven't been able to test it yet but by reading the code in the repo it looks like it is the case. Hope it helps!

**Comment by Gamote** [comment]
Hi @darquezt,

It helped indeed! I've published a new version with the fix. Thank for the info!
