### ISSUE TITLE
Can't work if set ref in useLottie 

### ISSUE THREAD

**Issue by Zaynex** [Gamote/lottie-react#17]
**Describe the bug**
Can't work if set ref in useLottie.

**To Reproduce**
```
export default function App() {
  const ref = React.useRef();
  const options = {
    animationData: groovyWalkAnimation,
    loop: true,
    autoplay: true,
    ref: ref
  };

  const { View } = useLottie(options);

  return (
    <>
      <h1>lottie-react - Hook</h1>
      {View}
    </>
  );
}
```

**Expected behavior**
Can get ref and useLottie work.

**Screenshots**
https://codesandbox.io/s/lottie-react-hook-forked-jgcfb?file=/src/App.js:146-502

**Packages**
- React: 16.13.1
- React-DOM: 16.13.1
- lottie-react: 2.1.0

**Comment by Gamote** [comment]
Hi @Zaynex, thank you for taking the time to report this. Indeed, there is a bug if you pass the `ref` property to `useLottie` because the internal `ref`, which is passed to Lottie, is overridden. This will be fixed in the next version (`v3`).

I would also like to mention that after the bug is fixed the presence of `ref` will do nothing as you already have the **interaction methods** if you want to control the animation.

**Comment by Zaynex** [comment]
I want  control the lottie element custom css transform. 
It works if I add parent element for `View`.
`<div>{View}</div>`

**Comment by Gamote** [comment]
@Zaynex you can't use `ref` as it's reserved for Lottie. In order to change the styling, you can use the second param of the `useLottie` hook like this:
```
useLottie(options, {
  height: 150,
});
```

For any other `div` property, you can use directly the `options` object. In the `v3` everything will be unified under a `containerProps`.
